DAC-480 [FE] Modification within Transaction by customer
input-output-hk/dapps-certification pull request #55
Opened 2023-03-01 14:27 UTC by amnambiar

https://input-output.atlassian.net/browse/DAC-480

2023-03-15 11:55 UTC, bogdan-manole requested changes

2023-03-15 11:55 UTC, bogdan-manole commented on react-web/src/components/CreateCertificate/CreateCertificate.tsx
> +export interface run {
only have one comment: I would remain consistent with upper case for the first letter in the case of types
same for (the `certificate`).

2023-03-17 13:29 UTC, RSoulatIOHK approved these changes
Bogdan had minor requests that were taken into account so I'm approving this PR.

2023-03-17 13:36 UTC, bogdan-manole approved these changes

2023-03-21 06:51 UTC, merged