PLT-4554 [FE]Sell a subscription
input-output-hk/dapps-certification pull request #60
Opened 2023-03-17 08:40 UTC by amnambiar

https://input-output.atlassian.net/browse/PLT-4554

2023-03-24 13:53 UTC, RSoulatIOHK commented
I think it still needs to have an actual effect when clicking on the different "pay" buttons to close PLT-4554. But it looks good. You should wait for the more expert review from Bogdan, this was just my 2 cents.

2023-04-12 11:56 UTC, bogdan-manole requested changes

2023-04-12 11:56 UTC, bogdan-manole commented on react-web/src/pages/subscription/Subscription.tsx
> +const developerTiers = [
Shouldn't we get the descriptions from `GET /tiers`?

2023-04-12 11:56 UTC, bogdan-manole commented on react-web/src/pages/subscription/components/PricingCard/PricingCard.tsx
> +const PricingCard: React.FC<any> = ({ name, disabled, featureSet, description, price }) => {
why `any` ?

2023-04-12 11:56 UTC, bogdan-manole commented on react-web/src/pages/subscription/components/PricingCard/PricingCard.tsx
> +          {/* <li>
do we need the comment?

2023-04-13 06:39 UTC, amnambiar commented
Closing this PR as most recent changes are included within https://github.com/input-output-hk/dapps-certification/pull/64

2023-04-13 06:39 UTC, closed without merging